# Generated by Django 3.2.6 on 2021-10-03 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RentalEquipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('needed_from', models.DateField()),
                ('needed_to', models.DateField()),
                ('rentals', models.ManyToManyField(to='RentalEquipment.Rental')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('rental_period', models.IntegerField()),
                ('invoice_amount', models.IntegerField()),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvoiceJob.job')),
            ],
        ),
    ]
