# Generated by Django 3.2.7 on 2021-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0006_auto_20211001_1508'),
        ('InvoiceJob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='rentals',
            field=models.ManyToManyField(to='RentalEquipment.Rental'),
        ),
    ]
