# Generated by Django 3.2.7 on 2021-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiptment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
