# Generated by Django 3.2.7 on 2021-10-01 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0002_alter_equiptment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieve_date', models.DateField(default=datetime.date.today)),
                ('buy_rent', models.BooleanField(choices=[(True, 'BUY'), (False, 'RENT')], default='BUY')),
                ('Equiptment', models.ManyToManyField(to='RentalEquipment.Equiptment')),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RentalEquipment.vendor')),
            ],
        ),
    ]
