# Generated by Django 3.2.6 on 2021-10-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0002_auto_20211002_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='recieve_time',
            new_name='receive_time',
        ),
    ]
