# Generated by Django 3.2.7 on 2021-10-01 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0003_rental_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='recieve_hours',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_hours',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='equiptment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
