# Generated by Django 3.2.7 on 2021-10-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalEquipment', '0004_auto_20211001_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='recieve_hours',
            new_name='recieve_time',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='return_hours',
            new_name='return_time',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='recieve_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_date',
        ),
    ]
